### ISSUE TITLE
sid_is_email causes issue in CSVReader

### ISSUE THREAD

**Issue by SohamPardeshi** [hschafer/teaching-toolshed#4]
https://github.com/hschafer/teaching-toolshed/blob/8502388e5c39093b278098bb4ac950788b587bbc/teachingtoolshed/gradebook/csv_readers.py#L41

I was running into an issue with this line because `split('@')` returns the entire Series. When we are indexing `[0]`, we aren't doing an elementwise operation but getting the first row of the Series. Switching to an apply worked for me.

**Comment by hschafer** [comment]
Could you do a `pip freeze` to show me what version of pandas you are on? Or could you send the snippet where you create the object? This has always worked for me and has done the element-wise operation but I could double check again.

**Comment by SohamPardeshi** [comment]
I think I'm using a relatively up-to-date version with `pandas==1.3.1` and `numpy==1.21.1`. I get the error when I try to parse `lessons.csv`  in a modified version of `update_canvas_gradebook.py`. I've made some modifications to the download/compute/upload files but I think they are unrelated to this issue since the emails should be in the same format. Specifically, I'm running

```python # Get the file path
checkpoint_path = os.path.join(OUTPUT_DIR, "lessons.csv")

# Look at every Ed checkpoint ID
for checkpoint_id in metadata["id"]:
    checkpoint_scores = CSVReader(
        checkpoint_path, sid_col="email", score_col=f"{checkpoint_id}", sid_is_email=True
    )
    canvas.add_grades(ed_to_canvas[checkpoint_id], checkpoint_scores)
```

Here, `lessons.csv` has the header `email,name,tutorial,#1,#2,total` where `#1` and `#2` are placeholders for the Edstem checkpoint IDs.

**Comment by hschafer** [comment]
Ah I see the change I made and it might have broken it.

The line as it was before was:

```python
df[self.sid_col] = df[email_col].str.split('@').str[0]
```

But my linter got mad at me since it didn't like using the `str` property to index.

Since I don't have easily accessible data to test this on with the fix, could you try this and let me know if it works?

```python
df[self.sid_col] = df[email_col].str.split('@', expand=True)[0]
```

[Source](https://stackoverflow.com/questions/29947574/splitting-at-underscore-in-python-and-storing-the-first-value)

**Comment by SohamPardeshi** [comment]
Yep! I tried the following
```python 
self.scores[self.sid_col] = self.scores[self.sid_col].str.split('@', expand=True)[0]
```
and it works perfectly 😄

**Comment by hschafer** [comment]
Okay, will push a fix now! Thanks for testing! I'm just too lazy to download an old Canvas Gradebook again haha :)
